package Persistencia;

import java.sql.SQLException;

public class BuildDeTabelas extends ConexaoComBancoDeDados {

    private final String tabelaPerfil = "CREATE TABLE IF NOT EXISTS PERFIL ("
            + "CODIGO INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 101, INCREMENT BY 1) ,"
            + "NOME VARCHAR(50) NOT NULL,"
            + "DESCRICAO VARCHAR(100) NOT NULL,"
            + "PRIMARY KEY(CODIGO));";

    private final String tabelaUsuario = "CREATE TABLE IF NOT EXISTS USUARIO ("
            + "ID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1),"
            + "CPF VARCHAR(13) NOT NULL,"
            + "NOME VARCHAR(50) NOT NULL,"
            + "USERNAME VARCHAR(30) NOT NULL,"
            + "SENHA VARCHAR(100) NOT NULL,"
            + "CODIGO_PERFIL INTEGER NOT NULL,"
            + "TELEFONE VARCHAR(15) NOT NULL,"
            + "MATRICULA VARCHAR(5) NOT NULL,"
            + "DATA_NASCIMENTO DATE NOT NULL,"
            + "PRIMARY KEY(ID),"
            + "FOREIGN KEY(CODIGO_PERFIL) REFERENCES PERFIL(CODIGO));";

    private final String sequenciaMatriculaTbUsuario = "CREATE SEQUENCE IF NOT EXISTS MATRICULA_SEQ  AS BIGINT START WITH  1000 INCREMENT BY 5;";

    private final String insertPerfis = "INSERT INTO PERFIL( "
            + "NOME, DESCRICAO)VALUES "
            + "('ADMINISTRADOR','SUPER USUÁRIO'),"
            + "('COMUM','USUÁRIO SOMENTE CONSULTA'),"
            + "('AVANÇADO','USUÁRIO CONSULTA E CADASTRA');";

    public void construirTabelas() throws SQLException {

        executarScript(tabelaPerfil);
        System.out.println("Tabela perfil criada com suscesso");

        executarScript(tabelaUsuario);
        System.out.println("Tabela Usuário criada com suscesso");

        executarScript(sequenciaMatriculaTbUsuario);
        System.out.println("Sequencia Matrícula Usuário criada com sucesso");

    }

    public void inserirDados() throws SQLException {

        System.out.println("Inserindo dados na tabela Perfil....");
        executarScript(insertPerfis);
        System.out.println("Dados de perfil inseridos com sucesso");

    }

}
